# Generated by Django 2.2.6 on 2019-11-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_auto_20191103_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PtgBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('time_begin', models.DateTimeField(verbose_name='booking time begin')),
                ('time_end', models.DateTimeField(verbose_name='booking time end')),
                ('cost', models.IntegerField()),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_location', to='ptgride.Location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location', to='ptgride.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.User')),
            ],
        ),
    ]
