# Generated by Django 2.2.6 on 2019-11-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=256)),
                ('from_city', models.CharField(max_length=256)),
                ('to_city', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
