# Generated by Django 2.2.6 on 2019-11-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_id',
            new_name='id',
        ),
    ]
