# Generated by Django 2.2.6 on 2019-11-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191103_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('address', models.CharField(max_length=256)),
                ('image', models.ImageField(height_field=200, max_length=255, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
